/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentType = IDL.Variant({
  'resume' : IDL.Null,
  'tamilContent' : IDL.Null,
  'blog' : IDL.Null,
  'script' : IDL.Null,
  'email' : IDL.Null,
  'story' : IDL.Null,
  'template' : IDL.Null,
  'socialMedia' : IDL.Null,
});
export const Tone = IDL.Variant({
  'funny' : IDL.Null,
  'casual' : IDL.Null,
  'emotional' : IDL.Null,
  'formal' : IDL.Null,
});
export const Length = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
  'medium' : IDL.Null,
});
export const Language = IDL.Variant({
  'tamil' : IDL.Null,
  'hinglish' : IDL.Null,
  'english' : IDL.Null,
});
export const GeneratedContent = IDL.Record({
  'id' : IDL.Text,
  'contentType' : ContentType,
  'tone' : Tone,
  'language' : Language,
  'length' : Length,
  'timestamp' : IDL.Int,
  'generatedText' : IDL.Text,
  'originalPrompt' : IDL.Text,
});
export const RewriteOptions = IDL.Record({
  'simplify' : IDL.Bool,
  'translate' : IDL.Bool,
  'makeProfessional' : IDL.Bool,
  'targetLanguage' : IDL.Opt(Language),
  'makeEmotional' : IDL.Bool,
});
export const RewriteRequest = IDL.Record({
  'originalText' : IDL.Text,
  'tone' : Tone,
  'language' : Language,
  'options' : RewriteOptions,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'generateContent' : IDL.Func(
      [ContentType, Tone, Length, Language, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllTemplates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getHistory' : IDL.Func([], [IDL.Vec(GeneratedContent)], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [IDL.Text], []),
  'rewriteText' : IDL.Func([RewriteRequest], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentType = IDL.Variant({
    'resume' : IDL.Null,
    'tamilContent' : IDL.Null,
    'blog' : IDL.Null,
    'script' : IDL.Null,
    'email' : IDL.Null,
    'story' : IDL.Null,
    'template' : IDL.Null,
    'socialMedia' : IDL.Null,
  });
  const Tone = IDL.Variant({
    'funny' : IDL.Null,
    'casual' : IDL.Null,
    'emotional' : IDL.Null,
    'formal' : IDL.Null,
  });
  const Length = IDL.Variant({
    'long' : IDL.Null,
    'short' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Language = IDL.Variant({
    'tamil' : IDL.Null,
    'hinglish' : IDL.Null,
    'english' : IDL.Null,
  });
  const GeneratedContent = IDL.Record({
    'id' : IDL.Text,
    'contentType' : ContentType,
    'tone' : Tone,
    'language' : Language,
    'length' : Length,
    'timestamp' : IDL.Int,
    'generatedText' : IDL.Text,
    'originalPrompt' : IDL.Text,
  });
  const RewriteOptions = IDL.Record({
    'simplify' : IDL.Bool,
    'translate' : IDL.Bool,
    'makeProfessional' : IDL.Bool,
    'targetLanguage' : IDL.Opt(Language),
    'makeEmotional' : IDL.Bool,
  });
  const RewriteRequest = IDL.Record({
    'originalText' : IDL.Text,
    'tone' : Tone,
    'language' : Language,
    'options' : RewriteOptions,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'generateContent' : IDL.Func(
        [ContentType, Tone, Length, Language, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllTemplates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getHistory' : IDL.Func([], [IDL.Vec(GeneratedContent)], ['query']),
    'getTemplate' : IDL.Func([IDL.Text], [IDL.Text], []),
    'rewriteText' : IDL.Func([RewriteRequest], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };