/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContentType = { 'resume' : null } |
  { 'tamilContent' : null } |
  { 'blog' : null } |
  { 'script' : null } |
  { 'email' : null } |
  { 'story' : null } |
  { 'template' : null } |
  { 'socialMedia' : null };
export interface GeneratedContent {
  'id' : string,
  'contentType' : ContentType,
  'tone' : Tone,
  'language' : Language,
  'length' : Length,
  'timestamp' : bigint,
  'generatedText' : string,
  'originalPrompt' : string,
}
export type Language = { 'tamil' : null } |
  { 'hinglish' : null } |
  { 'english' : null };
export type Length = { 'long' : null } |
  { 'short' : null } |
  { 'medium' : null };
export interface RewriteOptions {
  'simplify' : boolean,
  'translate' : boolean,
  'makeProfessional' : boolean,
  'targetLanguage' : [] | [Language],
  'makeEmotional' : boolean,
}
export interface RewriteRequest {
  'originalText' : string,
  'tone' : Tone,
  'language' : Language,
  'options' : RewriteOptions,
}
export type Tone = { 'funny' : null } |
  { 'casual' : null } |
  { 'emotional' : null } |
  { 'formal' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'generateContent' : ActorMethod<
    [ContentType, Tone, Length, Language, string],
    string
  >,
  'getAllTemplates' : ActorMethod<[], Array<[string, string]>>,
  'getHistory' : ActorMethod<[], Array<GeneratedContent>>,
  'getTemplate' : ActorMethod<[string], string>,
  'rewriteText' : ActorMethod<[RewriteRequest], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];