/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RewriteOptions {
    simplify: boolean;
    translate: boolean;
    makeProfessional: boolean;
    targetLanguage?: Language;
    makeEmotional: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface GeneratedContent {
    id: string;
    contentType: ContentType;
    tone: Tone;
    language: Language;
    length: Length;
    timestamp: bigint;
    generatedText: string;
    originalPrompt: string;
}
export interface RewriteRequest {
    originalText: string;
    tone: Tone;
    language: Language;
    options: RewriteOptions;
}
export interface http_header {
    value: string;
    name: string;
}
export enum ContentType {
    resume = "resume",
    tamilContent = "tamilContent",
    blog = "blog",
    script = "script",
    email = "email",
    story = "story",
    template = "template",
    socialMedia = "socialMedia"
}
export enum Language {
    tamil = "tamil",
    hinglish = "hinglish",
    english = "english"
}
export enum Length {
    long_ = "long",
    short_ = "short",
    medium = "medium"
}
export enum Tone {
    funny = "funny",
    casual = "casual",
    emotional = "emotional",
    formal = "formal"
}
export interface backendInterface {
    generateContent(contentType: ContentType, tone: Tone, length: Length, language: Language, prompt: string): Promise<string>;
    getAllTemplates(): Promise<Array<[string, string]>>;
    getHistory(): Promise<Array<GeneratedContent>>;
    getTemplate(templateName: string): Promise<string>;
    rewriteText(rewriteRequest: RewriteRequest): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ContentType as _ContentType, GeneratedContent as _GeneratedContent, Language as _Language, Length as _Length, RewriteOptions as _RewriteOptions, RewriteRequest as _RewriteRequest, Tone as _Tone } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async generateContent(arg0: ContentType, arg1: Tone, arg2: Length, arg3: Language, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateContent(to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tone_n3(this._uploadFile, this._downloadFile, arg1), to_candid_Length_n5(this._uploadFile, this._downloadFile, arg2), to_candid_Language_n7(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateContent(to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tone_n3(this._uploadFile, this._downloadFile, arg1), to_candid_Length_n5(this._uploadFile, this._downloadFile, arg2), to_candid_Language_n7(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async getAllTemplates(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTemplates();
            return result;
        }
    }
    async getHistory(): Promise<Array<GeneratedContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplate(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return result;
        }
    }
    async rewriteText(arg0: RewriteRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.rewriteText(to_candid_RewriteRequest_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rewriteText(to_candid_RewriteRequest_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ContentType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_GeneratedContent_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratedContent): GeneratedContent {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Length_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Length): Length {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Tone_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tone): Tone {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contentType: _ContentType;
    tone: _Tone;
    language: _Language;
    length: _Length;
    timestamp: bigint;
    generatedText: string;
    originalPrompt: string;
}): {
    id: string;
    contentType: ContentType;
    tone: Tone;
    language: Language;
    length: Length;
    timestamp: bigint;
    generatedText: string;
    originalPrompt: string;
} {
    return {
        id: value.id,
        contentType: from_candid_ContentType_n12(_uploadFile, _downloadFile, value.contentType),
        tone: from_candid_Tone_n14(_uploadFile, _downloadFile, value.tone),
        language: from_candid_Language_n16(_uploadFile, _downloadFile, value.language),
        length: from_candid_Length_n18(_uploadFile, _downloadFile, value.length),
        timestamp: value.timestamp,
        generatedText: value.generatedText,
        originalPrompt: value.originalPrompt
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resume: null;
} | {
    tamilContent: null;
} | {
    blog: null;
} | {
    script: null;
} | {
    email: null;
} | {
    story: null;
} | {
    template: null;
} | {
    socialMedia: null;
}): ContentType {
    return "resume" in value ? ContentType.resume : "tamilContent" in value ? ContentType.tamilContent : "blog" in value ? ContentType.blog : "script" in value ? ContentType.script : "email" in value ? ContentType.email : "story" in value ? ContentType.story : "template" in value ? ContentType.template : "socialMedia" in value ? ContentType.socialMedia : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    funny: null;
} | {
    casual: null;
} | {
    emotional: null;
} | {
    formal: null;
}): Tone {
    return "funny" in value ? Tone.funny : "casual" in value ? Tone.casual : "emotional" in value ? Tone.emotional : "formal" in value ? Tone.formal : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tamil: null;
} | {
    hinglish: null;
} | {
    english: null;
}): Language {
    return "tamil" in value ? Language.tamil : "hinglish" in value ? Language.hinglish : "english" in value ? Language.english : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
} | {
    medium: null;
}): Length {
    return "long" in value ? Length.long : "short" in value ? Length.short : "medium" in value ? Length.medium : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GeneratedContent>): Array<GeneratedContent> {
    return value.map((x)=>from_candid_GeneratedContent_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ContentType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Length_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Length): _Length {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RewriteOptions_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewriteOptions): _RewriteOptions {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_RewriteRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewriteRequest): _RewriteRequest {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Tone_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tone): _Tone {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    originalText: string;
    tone: Tone;
    language: Language;
    options: RewriteOptions;
}): {
    originalText: string;
    tone: _Tone;
    language: _Language;
    options: _RewriteOptions;
} {
    return {
        originalText: value.originalText,
        tone: to_candid_Tone_n3(_uploadFile, _downloadFile, value.tone),
        language: to_candid_Language_n7(_uploadFile, _downloadFile, value.language),
        options: to_candid_RewriteOptions_n22(_uploadFile, _downloadFile, value.options)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    simplify: boolean;
    translate: boolean;
    makeProfessional: boolean;
    targetLanguage?: Language;
    makeEmotional: boolean;
}): {
    simplify: boolean;
    translate: boolean;
    makeProfessional: boolean;
    targetLanguage: [] | [_Language];
    makeEmotional: boolean;
} {
    return {
        simplify: value.simplify,
        translate: value.translate,
        makeProfessional: value.makeProfessional,
        targetLanguage: value.targetLanguage ? candid_some(to_candid_Language_n7(_uploadFile, _downloadFile, value.targetLanguage)) : candid_none(),
        makeEmotional: value.makeEmotional
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    resume: null;
} | {
    tamilContent: null;
} | {
    blog: null;
} | {
    script: null;
} | {
    email: null;
} | {
    story: null;
} | {
    template: null;
} | {
    socialMedia: null;
} {
    return value == ContentType.resume ? {
        resume: null
    } : value == ContentType.tamilContent ? {
        tamilContent: null
    } : value == ContentType.blog ? {
        blog: null
    } : value == ContentType.script ? {
        script: null
    } : value == ContentType.email ? {
        email: null
    } : value == ContentType.story ? {
        story: null
    } : value == ContentType.template ? {
        template: null
    } : value == ContentType.socialMedia ? {
        socialMedia: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tone): {
    funny: null;
} | {
    casual: null;
} | {
    emotional: null;
} | {
    formal: null;
} {
    return value == Tone.funny ? {
        funny: null
    } : value == Tone.casual ? {
        casual: null
    } : value == Tone.emotional ? {
        emotional: null
    } : value == Tone.formal ? {
        formal: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Length): {
    long: null;
} | {
    short: null;
} | {
    medium: null;
} {
    return value == Length.long ? {
        long_: null
    } : value == Length.short ? {
        short_: null
    } : value == Length.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    tamil: null;
} | {
    hinglish: null;
} | {
    english: null;
} {
    return value == Language.tamil ? {
        tamil: null
    } : value == Language.hinglish ? {
        hinglish: null
    } : value == Language.english ? {
        english: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
